//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuongThaiKiet.DTKEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminACL
    {
        public long Id { get; set; }
        public int UserGroupId { get; set; }
        public Nullable<int> Domain { get; set; }
        public Nullable<int> Action { get; set; }
    
        public virtual AdminUserGroup AdminUserGroup { get; set; }
    }
}
