//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuongThaiKiet.DTKEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogCategoryEntry
    {
        public long Id { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<long> EntryId { get; set; }
    
        public virtual BlogCategory BlogCategory { get; set; }
        public virtual BlogEntry BlogEntry { get; set; }
    }
}
