//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuongThaiKiet.DTKEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DicDomainWord
    {
        public int Id { get; set; }
        public Nullable<int> DomainId { get; set; }
        public Nullable<int> WordId { get; set; }
    
        public virtual DicDomain DicDomain { get; set; }
        public virtual DicWord DicWord { get; set; }
    }
}
