//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuongThaiKiet.DTKEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DicDomainRef
    {
        public int Id { get; set; }
        public Nullable<int> DomainId { get; set; }
        public Nullable<int> ParentDomainId { get; set; }
    }
}
