//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuongThaiKiet.DTKEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DicIdiom
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Content { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual AdminUser AdminUser { get; set; }
    }
}
